#!/bin/bash

# Admin Account Creation Guide
# This script provides step-by-step instructions for creating admin accounts

echo "════════════════════════════════════════════════════════════════"
echo "  🔐 Admin Account Creation Guide"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "You're seeing 'auth/invalid-credential' because the admin accounts"
echo "don't exist in Firebase Authentication yet."
echo ""
echo "📋 SOLUTION: Create the accounts in Firebase Console"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 1: Open Firebase Console"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🌐 URL: https://console.firebase.google.com"
echo ""
echo "1. Login with your Google account"
echo "2. Select project: onchainweb-37d30"
echo ""

read -p "Press Enter when you've opened Firebase Console..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 2: Navigate to Authentication"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. In the left sidebar, click 'Authentication'"
echo "2. Click 'Users' tab at the top"
echo "3. You should see a list of users (might be empty)"
echo ""
echo "🌐 Direct URL:"
echo "https://console.firebase.google.com/u/0/project/onchainweb-37d30/authentication/users"
echo ""

read -p "Press Enter when you're on the Users page..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 3: Create Master Account"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Click 'Add user' button (top right)"
echo "2. Enter the following details:"
echo ""
echo "   📧 Email: master@admin.onchainweb.app"
echo "   🔑 Password: [Choose a STRONG password]"
echo ""
echo "   ⚠️  IMPORTANT: Remember this password!"
echo "   You'll use it to login to the master dashboard."
echo ""
echo "3. Click 'Add user'"
echo ""

read -p "Press Enter after creating the master account..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 4: Create Admin Account (Optional)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Click 'Add user' again"
echo "2. Enter:"
echo ""
echo "   📧 Email: admin@admin.onchainweb.app"
echo "   🔑 Password: [Choose a STRONG password]"
echo ""
echo "3. Click 'Add user'"
echo ""

read -p "Press Enter after creating the admin account (or skip)..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 5: Verify Accounts Created"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "You should now see both accounts in the Users list:"
echo ""
echo "   ✅ master@admin.onchainweb.app"
echo "   ✅ admin@admin.onchainweb.app"
echo ""

read -p "Press Enter to continue..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 6: Test Login"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Now try logging in:"
echo ""
echo "Master Dashboard:"
echo "  🌐 http://localhost:5173/master-admin"
echo "  👤 Username: master"
echo "  🔑 Password: [the password you just created]"
echo ""
echo "Admin Dashboard:"
echo "  🌐 http://localhost:5173/admin"
echo "  👤 Username: admin"
echo "  🔑 Password: [the password you just created]"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Setup complete! Try logging in now."
echo ""
echo "💡 TIP: You can also login with the full email:"
echo "   Example: master@admin.onchainweb.app"
echo ""
echo "📖 Need help? Check:"
echo "   - ADMIN_SETUP_GUIDE.md"
echo "   - MASTER_PASSWORD_SETUP.md"
echo "   - FIREBASE_ADMIN_IMPLEMENTATION.md"
echo ""
